# Site settings
title: Blog of Bob Young
email: bob.yang.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. This site shares technologies I have learned 
  and interesting things I am doing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yangbo.github.io" # the base hostname & protocol for your site
twitter_username: yangbo
github_username:  yangbo

# Build settings
markdown: kramdown
